### ISSUE TITLE
关于 highlight.js 和 instantclick.js冲突的问题

### ISSUE THREAD

**Issue by helloxz** [WarnerYang/typecho_themes#12]
博主，您好，查看您主题是用了 highlight.js 和 instantclick.js，并且没有冲突。但是当我尝试在自己的博客用这两个js库问题的时候发现instantclick.js预加载的页面并没有完成 highlight.js 的代码渲染（也就没有代码高亮），必须再次刷新页面才能完成highlight.js 代码高亮，请问如何解决呢？

**Comment by helloxz** [comment]
参考了您`main.js`里面的代码，问题已经解决，感谢。

**Comment by WarnerYang** [comment]
好的 感谢支持
