### ISSUE TITLE
提交文章评论需要提交两次

### ISSUE THREAD

**Issue by sunxiyuan** [WarnerYang/typecho_themes#2]
博主，首先感谢你把这么优秀的主题放出来给大家用。
在使用过程中，我发现这款主题无法为文章添加评论（需要提交两次评论才能提交上）
希望可以抽时间修正下这个问题，再次感谢。

**Comment by yavon007** [comment]
你把设置里的那个反垃圾关掉试试

**Comment by sunxiyuan** [comment]
如你所说，正常了，哈哈哈，美滋滋
