### ISSUE TITLE
index.php首页发布时间多了一个空格

### ISSUE THREAD

**Issue by ghost** [WarnerYang/typecho_themes#8]
`<?php _e('时间: '); ?><time datetime="<?php $this->date('c'); ?>" itemprop="datePublished"><?php $this->date('Y -m-d'); ?></time>`
\ \ \ \ \ \ \ \ \ \  ↑
              这里多了一个空格
by. 一个强迫症的发现

**Comment by WarnerYang** [comment]
https://github.com/WarnerYang/typecho-theme-Minimalism/commit/e2311692d00c6633f268ce5be8e27a86a97e1e42#diff-828e0013b8f3bc1bb22b4f57172b019d
