### ISSUE TITLE
之前的bing图片及json不会被自动删除

### ISSUE THREAD

**Issue by FlickerMi** [WarnerYang/typecho_themes#9]
之前的bing图片及json不会被自动删除，请问可能是什么原因导致？

**Comment by WarnerYang** [comment]
默认删除前30天的

**Comment by FlickerMi** [comment]
> 默认删除前30天的

我的一直没被删除过，所有图片都还在。

**Comment by FlickerMi** [comment]
@WarnerYang 请问是什么问题，我的一直没被删除过，所有图片都还在。是文件夹权限的问题吗，导致未被删除？

**Comment by WarnerYang** [comment]
> @WarnerYang 请问是什么问题，我的一直没被删除过，所有图片都还在。是文件夹权限的问题吗，导致未被删除？

如果必要，可以用定时任务清理下

**Comment by FlickerMi** [comment]
@WarnerYang 好吧
